package:
  name: shot-detector
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - pyav
  run:
    - python

test:
  imports:
    -

about:
  home:
  license:
  license_file:
